---
- name: Install the environment on the server
  hosts: prod_servers
  become: yes

  tasks:
    - name: Install tree command
      apt: name=tree state=latest

    - name: Install curl command
      apt: name=curl state=latest

    - name: Install git
      apt: name=git state=latest

    - name: Populate service facts
      ansible.builtin.service_facts:

    - block:
        - name: Install Docker
          ansible.builtin.get_url:
            url: "https://get.docker.com"
            dest: "/tmp/get-docker.sh"
            mode: 'u+x,g+x'
        - name: Run the Docker installation script
          ansible.builtin.command: sh /tmp/get-docker.sh
          args:
            creates: /usr/bin/docker
        - name: Add current user to docker group
          ansible.builtin.user:
            name: "{{ USER }}"
            groups: docker
      when: ansible_facts.services["docker.service"] is not defined

    - name: Install python3-pip package
      apt: name=python3-pip state=present

    - name: Install docker python package
      ansible.builtin.pip:
        name: docker

    - name: Download docker-compose
      shell: |
        curl -LO https://github.com/docker/compose/releases/download/v2.2.3/docker-compose-linux-x86_64
        chmod +x ./docker-compose-linux-x86_64
        mv ./docker-compose-linux-x86_64 /usr/local/bin/docker-compose
      args:
        creates: /usr/local/bin/docker-compose

    - name: Download minikube
      shell: |
        curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        chmod +x ./minikube
        mv ./minikube /usr/local/bin/minikube
      args:
        creates: /usr/local/bin/minikube

    - name: Download kubectl
      shell: |
        curl -LO https://dl.k8s.io/release/`curl -LS https://dl.k8s.io/release/stable.txt`/bin/linux/amd64/kubectl 
        chmod +x ./kubectl
        mv ./kubectl /usr/local/bin/kubectl
      args:
        creates: /usr/local/bin/kubectl

    - name: Check if jenkins_server image exists
      community.docker.docker_image_info:
        name: jenkins_server
      register: image_info

    - block:
        - name: Clone gsk-16-infra repository
          git:
            repo: https://github.com/SergeyPoletaev/gsk-16-infra
            dest: /tmp/gsk-16-infra
        - name: Build jenkins_server image
          community.docker.docker_image:
            build:
              path: /tmp/gsk-16-infra/jenkins/server
            tag: jenkins_server
            source: build
        - name: Run the jenkins_server container
          community.docker.docker_container:
            name: jenkins_server
            image: jenkins_server
            ports:
              - "9090:8080"
              - "50000:50000"
            volumes:
              - "/var/run/docker.sock:/var/run/docker.sock"
              - "/tmp:/var/jenkins_home"
            detach: true
        - name: Stop the jenkins_server container
          community.docker.docker_container:
            name: jenkins_server
            state: stopped
      when: image_info.images|length == 0






